In [2]:
import numpy as np
import pandas as pd

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [4]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [18]:
a.reshape(12, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [17]:
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [19]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [20]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [22]:
a.reshape(12, -1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [23]:
a.reshape(6, -1)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [24]:
a.reshape(4, -1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [25]:
a.reshape(-1, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
a.reshape(-1, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [30]:
isinstance(a.reshape(1,-1)[0], int)

False

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [34]:
arr = np.random.randn(3, 4)
arr.flatten()

array([ 0.91650881,  0.87151348, -0.46896028, -0.68229278, -0.22319155,
        0.75493089,  0.92690375, -0.54974627, -0.6759382 , -0.51211388,
       -2.30372178,  0.41735334])

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [38]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [48]:
b = np.arange(20, 1, -2).reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [47]:
if(not isinstance(a[0], type(b[0]))):
    print("a - одномерный массив. b - двумерный массив")

a - одномерный массив. b - двумерный массив


Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [61]:
a = np.zeros((2, 2))
b = np.ones((3, 2))

v = np.vstack((a,b))

v.size

10

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [77]:
a = np.arange(0,12)
A = a.reshape(4,3)
At = A.T

B = A.dot(At)

if(np.linalg.det(B) == 0):
    print("Для матрицы с определителем == 0, обратной матрицы нет")

Для матрицы с определителем == 0б обратной матрицы нет


 Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [78]:
np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [84]:
c = np.random.randint(0, 16, (16,))
c

array([11, 12,  7, 14,  2, 13,  0,  3,  1,  7,  3,  1, 13,  5,  5,  9])

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [95]:
C = c.reshape(4, 4)
D = B + C * 10

D_inv = np.linalg.inv(D)
D_rank = np.linalg.matrix_rank(D)
D_det = np.linalg.det(D)

print(f"Определитель: {D_det}")
print(f"Ранг: {D_rank}")
print(f"Обратная матрица:\n{D_inv}")

Определитель: 73961599.99999985
Ранг: 4
Обратная матрица:
[[ 0.02323151 -0.01631874  0.00835028 -0.00859473]
 [ 0.00953143  0.00029096  0.00698308 -0.00824969]
 [ 0.02632934 -0.03186194  0.03531346 -0.01919699]
 [-0.03138061  0.02791178 -0.03011725  0.02255332]]


Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [106]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1

E = np.where(D_inv, B, C)
E

array([[  5,  12,  23,  14],
       [ 14,  50,  86,   3],
       [ 23,   7, 149,   1],
       [ 13, 122,   5, 302]])